"$schema": https://json-schema.org/draft/2020-12/schema
description: 'SOSA Platform'
x-jsonld-context: ../../../sosa-ssn.jsonld
$defs:
  Platform:
    allOf:
      - $ref: bblocks://ogc.sosa.properties.registerItem
      - type: object
        properties:
          hosts:
            type: array
            items:
              anyOf:
                - $ref: bblocks://ogc.ogc-utils.iri-or-curie
                - $ref: '#/$defs/Platform'
                - $ref: bblocks://ogc.sosa.properties.system
allOf:
  - $ref: '#/$defs/Platform'
