"$schema": https://json-schema.org/draft/2020-12/schema
description: 'SOSA System'
x-jsonld-context: ../../../sosa-ssn.jsonld
$defs:
  System:
    anyOf:
      - $ref: bblocks://ogc.ogc-utils.iri-or-curie
      - type: object
        properties:
          id:
            $ref: bblocks://ogc.ogc-utils.iri-or-curie
          name:
            type: string
          implements:
            type: array
            items:
              $ref: bblocks://ogc.sosa.properties.procedure
          hasSubSystem:
            type: array
            items:
              $ref: '#/$defs/System'
          isSubSystemOf:
            $ref: '#/$defs/System'
          isHostedBy:
            $ref: bblocks://ogc.ogc-utils.iri-or-curie
allOf:
  - $ref: '#/$defs/System'
