"$schema": https://json-schema.org/draft/2020-12/schema
description: 'SOSA System'
x-jsonld-context: ../../../sosa-ssn.jsonld
$defs:
  System:
    allOf:
      - $ref: bblocks://ogc.sosa.properties.registerItem
      - type: object
        properties:
          implements:
            type: array
            items:
              anyOf:
                - $ref: bblocks://ogc.ogc-utils.iri-or-curie
                - $ref: bblocks://ogc.sosa.properties.procedure
          hasSubSystem:
            type: array
            items:
              anyOf:
                - $ref: bblocks://ogc.ogc-utils.iri-or-curie
                - $ref: '#/$defs/System'
          isSubSystemOf:
            anyOf:
              - $ref: bblocks://ogc.ogc-utils.iri-or-curie
              - $ref: '#/$defs/System'
          isHostedBy:
            $ref: bblocks://ogc.ogc-utils.iri-or-curie
allOf:
  - $ref: '#/$defs/System'
