"$schema": https://json-schema.org/draft/2020-12/schema
description: 'SOSA Property'
x-jsonld-context: ../../../sosa-ssn.jsonld
$defs:
  Property:
    allOf:
      - $ref: bblocks://ogc.sosa.properties.registerItem
      - type: object
        properties:
          isPropertyOf:
            anyOf:
              - $ref: bblocks://ogc.ogc-utils.iri-or-curie
              - $ref: bblocks://ogc.sosa.properties.featureOfInterest
          hasProcedure:
            type: array
            items:
              anyOf:
                - $ref: bblocks://ogc.ogc-utils.iri-or-curie
                - $ref: bblocks://ogc.sosa.properties.procedure
allOf:
  - $ref: '#/$defs/Property'
