"$schema": https://json-schema.org/draft/2020-12/schema
description: 'SOSA Sensor'
x-jsonld-context: ../../../sosa-ssn.jsonld
$definitions:
  Sensor:
    #TBD - need to blow this away and build using model
    # sosa:madeObservation ONLY (sosa:Observation or sosa:ObservationCollection)
    # sosa:observes ONLY sosa:Property
    # sosa:detects ONLY sosa:Stimulus
    # sosa:implements ONLY sosa:ObservingProcedure
    anyOf:
      - $ref: bblocks://ogc.ogc-utils.iri-or-curie
      - type: object
        properties:
          id:
            $ref: bblocks://ogc.ogc-utils.iri-or-curie
          name:
            type: string
allOf:
  - $ref: '#/$definitions/Sensor'