"$schema": https://json-schema.org/draft/2020-12/schema
description: 'SOSA Sensor'
x-jsonld-context: ../../../sosa-ssn.jsonld
$defs:
  Sensor:
    allOf:
      - $ref: bblocks://ogc.sosa.properties.system
      - type: object
        properties:
          observes:
            type: array
            items:
              anyOf:
                - $ref: bblocks://ogc.ogc-utils.iri-or-curie
                - $ref: bblocks://ogc.sosa.properties.property
allOf:
  - $ref: '#/$defs/Sensor'
