"$schema": https://json-schema.org/draft/2020-12/schema
description: 'SOSA ObservationCollection'
x-jsonld-context: ../../../sosa-ssn.jsonld
$defs:
  collection:
    allOf:
      - $ref: bblocks://ogc.sosa.properties.observation-owa
      - type: object
        properties:
          hasMember:
            type: array
            items:
              anyOf:
                - $ref: '#/$defs/collection'
                - $ref: bblocks://ogc.sosa.properties.observation
                - $ref: bblocks://ogc.ogc-utils.iri-or-curie
allOf:
  - $ref: '#/$defs/collection'
  - not:
      anyOf:
        - required:
            - hasResult
        - required:
            - hasSimpleResult
