"$schema": https://json-schema.org/draft/2020-12/schema
description: 'SOSA Procedure'
x-jsonld-context: ../../../sosa-ssn.jsonld
$defs:
  Procedure:
    allOf:
      - $ref: bblocks://ogc.sosa.properties.registerItem
      - type: object
        # TBD - should this have a required set
        # TBD name and description?
        properties:
          implementedBy:
            type: array
            items:
              anyOf:
                - $ref: bblocks://ogc.ogc-utils.iri-or-curie
                - $ref: bblocks://ogc.sosa.properties.system
          hasInput: true
          hasOutput: true
          isProcedureFor:
            type: array
            items:
              anyOf:
                - $ref: bblocks://ogc.ogc-utils.iri-or-curie
                - $ref: bblocks://ogc.sosa.properties.property
allOf:
  - $ref: '#/$defs/Procedure'
