"$schema": https://json-schema.org/draft/2020-12/schema
description: 'SOSA Observation'
x-jsonld-context: ../../../sosa-ssn.jsonld
allOf:
  - $ref: bblocks://ogc.sosa.properties.execution
  - type: object
    properties:
      observedProperty:
        $ref: bblocks://ogc.sosa.properties.observableProperty
      madeBySensor:
        $ref: bblocks://ogc.sosa.properties.sensor
      hasResult: true
      result: true
      result@links: true
      hasSimpleResult: true
